### PR TITLE
Some examples of how to use the library

### PR DESCRIPTION
**Pull request by poldy**
I was thinking of writing a blog post on how to use your library, but thought some quick source code would be more useful. Thanks for the work!

### CODE REVIEW

**Comment by AlaskanEmily** [comment]
(As a quick note, most development of this library takes place at https://osdn.net/projects/transunit/ now)

This would be welcome, but a few notes:

It should follow the coding style of the rest of the package. Particularly:
1. Except when an operator is being used, prefer `use_module` to `import_module` (so in this case, all modules except `int`)
2. Separator comments (the `%=== ... ===%` and `%--- ... ---%` comments) should be added to help with readability.
3. All pred should use snake-case (so `checkMaths` should become `check_maths`).
4. I'd prefer if lines were kept to 79 columns where possible. It's not a huge deal for code, but this should always be the case in comments.

I'm also unsure why the `require` import?

I am fine with accepting change this as-is, and then reformatting it myself to match the style if you would like me to. I haven't published a style guide, so it's not really fair if I require this change to meet that.

What this does definitely need is a license applied. I would prefer that example code be in the public domain or zlib, but at the very least it needs a license header at the top of the file.

**Comment by poldy** [comment]
Thanks for your feedback, I'm still learning Mercury so it was educational. I think I took care of your comments, but if not feel free to edit yourself.

I tried to use the osdn site, but it was very slow/unresponsive, I think it might be being DDOS'd :-( If you're moving the hosting provider, I'd suggest putting a large notice to that effect at the top of the README, and maybe disabling the issue tracker, forks & PRs? Perhaps there's some option to "archive" a project.

**Comment by poldy** [comment]
I finally crossed this item off my to-do list, and moved the patch to the new OSDN project ( https://osdn.net/projects/transunit/ticket/48606 )

**Comment by AlaskanEmily** [comment]
Sorry I was kind of absent, I'll accept this here too since I expect more people to find the project through github.
I should really sync up the two or setup automatic mirroring.

**Comment by AlaskanEmily** [comment]
Also as a note on github versus OSDN: I originally moved to OSDN because I just generally don't like github the company. OSDN's forum system is being used as free data storage by groups taking advantage of what is essentially a free service that the company doesn't seem interesting in moderating or maintaining anymore, so I'll likely have to move to another service from OSDN soon in any case.

**Pull request merged**
